// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Shortening.Models;

namespace Shortening.Migrations
{
    [DbContext(typeof(MapDbContext))]
    partial class MapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("UrlShorten.Models.MappedItem", b =>
                {
                    b.Property<string>("Alias")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16);

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Alias");

                    b.HasIndex("Alias");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
